### ISSUE TITLE
typo? ("OOCSSにより嫌いになりかけ")

### ISSUE THREAD

**Issue by kubosho** [hail2u/hail2u.net#2]
https://github.com/hail2u/hail2u.net/blob/f998daff9b67ba61263503c04334e0917df38d20/blog/webdesign/oocss-drawbacks-and-gifts-of-every-declaration-just-once.html#L217

上記の行に書かれている「OOCSSにより嫌いになりかけ」という文章ですが「OOCSSをより嫌いになりかけ」と書きたかったのではないかと思いました。

**Comment by hail2u** [comment]
「OOCSSにより嫌いになりかけ」と「Sassでかろうじて理性を保っていた」が両方共つづく「CSS」という単語にかかるつもりで書いてました。ちょっと区切りが変なのとわかりにくそうなので直します。

**Comment by kubosho** [comment]
新しい表現分かりやすいと思います :+1:
